language: node_js
sudo: false
node_js:
- '7.9.0'

git:
  depth: 5

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
